#include<iostream>
using namespace std;

//function to return the tax amount
float taxAmount(float income, float taxRate = 10.0) {
	return ((taxRate / 100) * income);
}

int main() {

	//test generated without providing the taxRate argument
	int income;
	cout << "Enter the income :- ";
	cin >> income;
	cout << taxAmount(income) << "\n";

	//test generated by providing the taxRate argument
	int taxRate;
	cout << "Enter the income and tax Rate respectively :- ";
	cin >> income >> taxRate;
	cout << taxAmount(income, taxRate) << " ";

	return 0;
}